[build]
command = "yarn install --frozen-lockfile && yarn build && zola build"
publish = "public"

[build.environment]
ZOLA_VERSION = "0.19.2"

[context.production.environment]
ZOLA_BASE_URL = "https://pythontorust.netlify.app/"
